### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by hubgit** [styled-components/css-to-react-native#100]
While trying to track down a dependency on `fbjs` I found that a) the last couple of versions of `css-to-react-native` published to npm aren't listed in [the release history](https://github.com/styled-components/css-to-react-native/releases) (I guess a tag wasn't created/pushed) and b) the dependency on fbjs was removed [a while ago](https://github.com/styled-components/css-to-react-native/commit/f45b72c4f16d7dceb039e6236612059de11b29f9) but not yet published.

Would it be possible to publish a new version (and tag, for the release history)?

**Comment by jacobp100** [comment]
Published under 2.3.0
