### ISSUE TITLE
Parsing errors from tailwind default config

### ISSUE THREAD

**Issue by m11m** [styled-components/css-to-react-native#114]
I had a parsing error on the following css:

```
flex: 1 1 0%;
```

I'm pretty sure this is legal css, the unit (% in this case) is optional?

Error printed out as:

`Error: Failed to parse declaration "flex: 1 1 0%"`

Here is the line in tailwind default config, I can work around this, but maybe it makes sense to support optional units on 0  ¯\_(ツ)_/¯ :

https://github.com/tailwindcss/tailwindcss/blob/beff1383533973baeb33436d7c31651b9ea751a8/stubs/defaultConfig.stub.js#L209

**Comment by jacobp100** [comment]
This one is actually a bug! I'll try and get it fixed within the next few days
