### ISSUE TITLE
Problems parsing boxShadow

### ISSUE THREAD

**Issue by m11m** [styled-components/css-to-react-native#115]
Error when parsing some from the following:

https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L185

Example:

`default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)'`

Results in error:

`error: bundling failed: Error: Failed to parse declaration "boxShadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)"`

**Comment by jacobp100** [comment]
React native only supports one box shadow, so we don’t handle parsing more than that
