### ISSUE TITLE
Problems parsing fontFamily

### ISSUE THREAD

**Issue by m11m** [styled-components/css-to-react-native#116]
Error when parsing some from the following:

https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L222

Example:

```
fontFamily: {
      serif: [
        'Georgia',
        'Cambria',
        '"Times New Roman"',
        'Times',
        'serif',
      ]
}
```

Results in error:

`error: bundling failed: Error: Failed to parse declaration "fontFamily: Georgia, Cambria, "Times New Roman", Times, serif"`

**Comment by jacobp100** [comment]
React native only supports one font family, so we don’t handle parsing more than that
