### ISSUE TITLE
Data type judgment and optimization

### ISSUE THREAD

**Issue by AZQD** [styled-components/css-to-react-native#124]
If shorthandblacklist, the second parameter of the tranform function, misuses a string, such as' fontmargin ', abbreviations are also allowed.

Maybe it's more rigorous to add typescript or verify data type here.
https://github.com/styled-components/css-to-react-native/blob/master/src/index.js#L85

**Comment by jacobp100** [comment]
Yeah, that's a good should. Maybe we should remove the default argument, then `Array.isArray(shorthandBlacklist) && shorthandBlacklist.includes(…)` - we should get a perf win from that too

**Comment by jacobp100** [comment]
Gonna close this, but feel free to submit a PR if you want
