### ISSUE TITLE
box-shadow does not work in react-native

### ISSUE THREAD

**Issue by Gustavoohrq** [styled-components/css-to-react-native#128]
I am using React.Native, I put the box-shadow but it does not work at all. I tested other codes but none worked.

`            import styled from 'styled-components/native'

            export const Box = styled.View`
                border-radius: 10;
                height: 150;
                width: 300;
                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.15);

            `;

            export const Title = styled.Text`

                color: #4b1b5f;
                font-size: 25px;
                font-weight: 900;

            `;

`

**Comment by jacobp100** [comment]
You’re doing the right thing in your example. It’ll only work on iOS though, as android doesn’t have support for custom shadows
