### ISSUE TITLE
React Native "Expected style to contain units"?

### ISSUE THREAD

**Issue by GollyJer** [styled-components/css-to-react-native#130]
## Environment
styled-components-v5.0.0-rc.1

## System:
 - OS: Windows 10
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 
 - Memory: 13.38 GB / 31.74 GB
## Binaries:
 - Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD

(node:5856) UnhandledPromiseRejectionWarning: Error: The system cannot find the path specified.

## Reproduction
I'm seeing these "contain unit" warning on every component that I style.
![image](https://user-images.githubusercontent.com/689204/69095046-63e11b80-0a06-11ea-8197-96f20f6269dc.png)

The code is straight forward.
```css
export const ModalContainer = styled.View`
  border-color: black;
  border-width: 2;
  border-top-left-radius: 20;
  border-top-right-radius: 20;
  height: 90%;
  margin-left: 2%;
  margin-right: 2%;
  overflow: hidden;
`;
```

What am I doing wrong? Is there a bug?

Thanks! 👍
Jeremy

**Comment by jacobp100** [comment]
This is the right repo for this issue, but we have issue #40 already, which contains more information. I’ll close this as a duplicate
