### ISSUE TITLE
Feature the web solution

### ISSUE THREAD

**Issue by jamesgeorge007** [styled-components/css-to-react-native#134]
In regard to https://github.com/styled-components/css-to-react-native/issues/131#issuecomment-570300964 I was of the thought to build a CLI solution which would be handy for sure. Later, I realized that a web solution would make much sense that resulted in https://csstox.surge.sh

Please see the repository [here](https://github.com/jamesgeorge007/csstox)

It would be great if the respective web solution was featured as part of the `README.md` so that people can get their job done with ease.

**Comment by jamesgeorge007** [comment]
\cc @jacobp100

**Comment by jacobp100** [comment]
Neat!

**Comment by jamesgeorge007** [comment]
Shall I shoot a PR in the above regard?
