### ISSUE TITLE
Support vh and vw units

### ISSUE THREAD

**Issue by Sharcoux** [styled-components/css-to-react-native#138]
Hi,

I think we should be able to support vh and vw units by replacing `Xvh` by `X * Dimensions.get('window').height / 100` and `Xvw` by `X * Dimensions.get('window').width / 100`, can't we?

**Comment by Sharcoux** [comment]
Check this out: https://github.com/DriveWealth/gulp-react-native-stylesheet-css/issues/2

**Comment by jacobp100** [comment]
I'm guessing this issue more asking for vw/vh support in styled components. There's not much this library can do to add support there - it's up to styled components to add support for it in their runtime

My styled-components clone supports it (https://jacobp100.github.io/cssta/css-support/) - so it is definitely possible for support to be added!

I'll close this issue as there's nothing we can do here to support it, but feel free to continue the discussion or ask any other questions

**Comment by Sharcoux** [comment]
Oh, sorry then, I thought it was the right project to target. Ok, I'll move it there.

**Comment by jacobp100** [comment]
There’s probably an issue already. It’s a common feature request

**Comment by Sharcoux** [comment]
Yeah, I found it. Seems on stand by for now. I'll try to understand exactly how it should be done, see if I can give it a try.
