### ISSUE TITLE
How do I add bottom border?

### ISSUE THREAD

**Issue by resting** [styled-components/css-to-react-native#140]
Have the following component, but the border bottom doesn't appear

```javascript
const StyledForgotPasswordText = styled.Text`
  font-size: 14px;
  text-align: right;
  border-bottom-color: black;
  border-bottom-width: 2px;
`;
```

The generated CSS [here](https://csstox.surge.sh/) looks fine:
```css
{
  "fontSize": 14,
  "textAlign": "right",
  "borderBottomColor": "black",
  "borderBottomWidth": 2
}
```

**Comment by jacobp100** [comment]
You can’t borders on text elements in react native

**Comment by resting** [comment]
I'm on react-native 0.62. Looks like it's possible.
Have tried adding the style to the title on the [docs](https://reactnative.dev/docs/text)
![image](https://user-images.githubusercontent.com/350530/80077912-bf4ca200-8580-11ea-9aec-bd03feb4c717.png)

**Comment by jacobp100** [comment]
The output you pasted looks fine, so we’re doing the right thing in this library

You can try putting that style directly into RN, because I think you can’t put borders on text and that the docs might be wrong

**Comment by resting** [comment]
You're right. Sorry, the preview was on web.
Just realize my mistake when it shows on Android while testing it.
I suppose best practice now is to just use `View` instead. Thanks!

**Comment by jacobp100** [comment]
Glad I could help - if only a little! 😄

**Comment by GonzaloTD360** [comment]
> I'm on react-native 0.62. Looks like it's possible. Have tried adding the style to the title on the [docs](https://reactnative.dev/docs/text) ![image](https://user-images.githubusercontent.com/350530/80077912-bf4ca200-8580-11ea-9aec-bd03feb4c717.png)

It works, u're awesome
