### ISSUE TITLE
[feature request] Add support to do reverse

### ISSUE THREAD

**Issue by selrond** [styled-components/css-to-react-native#144]
Usecase:
I have a custom styled component, where I want to use third-party styles (which are in `style` object form) alongside my styles and functions:

```js
const MyComponent = styled(SomeComponent)`
  font-size: 16px;
  ${({ color }) => color && `color: ${color}`}
`

Text.defaultProps = {
  style: thirdPartyStyleObject,
  color: '#FAFAFA', // doesn't work if color is defined inside `thirdPartyStyleObject`
}
```

The solution would be to be able to convert `thirdPartyStyleObject` to css string, which could be used inside my styled component.

Is there any other solution that I'm unaware of?

**Comment by jacobp100** [comment]
Could you elaborate a bit more? I can’t work out what you’re trying to do

**Comment by selrond** [comment]
@jacobp100 I want to use third party style alongside custom css inside styled component - so a style object alongside a css template literal. How would you do that?

**Comment by jacobp100** [comment]
If you look at the readme for this project, we take an array of style tuples - like `[["color", "red"], ["padding", "3px 5px"]]`, and then return a valid style object.

If you write some code to convert your CSS to that format, you can use the style object we give you. The easiest (but not 100% correct) thing is,

```js
const css = `
  color: red;
  padding: 3px 5px;
`
const styleTuples = css
  .split(/\s*;\s*/g)
  .map(line => line.split(/\s*:\s*/g))
  .filter(tuple => tuple.length === 2)
const styleObject = cssToReactNative(styleTuples)
```

**Comment by selrond** [comment]
But I don't need the style object. I need the ability to "merge" styles from the third-party `style` object with styled components

**Comment by jacobp100** [comment]
You can look at these,

* https://styled-components.com/docs/basics#extending-styles
* https://gist.github.com/carlosepp/7704cce24edba0520eb6b36d894f04ae

But at this point, you're talking about styled component issues. If you're still stuck, could you open this issue on their repo?

**Comment by selrond** [comment]
@selrond I'm talking about s-c issues, because you've asked me to elaborate. 
The question remains - could this lib be extended to do the opposite to what it does now? `react-native-to-css`

**Comment by jacobp100** [comment]
> could this lib be extended to do the opposite to what it does now

I personally don't have much interest in taking that task on. If someone else wanted to do this, I would say do it in a separate project - I want to keep this project limited to what's in the name

But I also expect this to be impossible to implement correctly - there's no way to convert `{ padding: 5 }` to CSS without changing the behaviour

**Comment by jacobp100** [comment]
Also, styled components has some form of support for objects - see https://styled-components.com/docs/advanced#style-objects
