### ISSUE TITLE
Add needsUnit to false for the project - v5

### ISSUE THREAD

**Issue by Pierre-CLIND** [styled-components/css-to-react-native#146]
Since :
https://github.com/styled-components/styled-components/pull/2811

And the v5 .

I have many errors in my code, it's possible to change "needsUnit" to false for the project?

I want to use ReactNative directly without styled-components units

![image](https://user-images.githubusercontent.com/56550362/89398368-4f1df280-d711-11ea-8bcd-17791b6d4f4a.png)

**Comment by jacobp100** [comment]
We're not looking to re-enable support for omitting units where they're required in CSS. If you want more information, you'll find some reasonings for this in past issues and PRs
