### ISSUE TITLE
Hi, does this library include a sanitizer or validator  

### ISSUE THREAD

**Issue by joseDaKing** [styled-components/css-to-react-native#149]
Hi, wonder if this library includes sanitizer for removing css prop or values that cannot be used with react native? The reason I need sanitizer library is because I am trying to port tailwindcss to RN. There are already a tailwindcss library for RN but the library do not have many features. The way I want to port the library is by compiling the generated tailwindcss file to js file that consists of RN style sheets. When I before I compile the CSS file I need way to sanitize it.

**Comment by jacobp100** [comment]
It doesn’t. You’ll need to do that processing before!

**Comment by joseDaKing** [comment]
@jacobp100 alright then, thanks for the answer, by the way do you know if there are library that already does that ?

**Comment by jacobp100** [comment]
I don’t think there’s a library that would to that. Different react native components accept different style props, so I’m not really sure how it would work to be honest.

**Comment by jacobp100** [comment]
Going to close this issue but you’re welcome to ask more questions if you need any pointers.
