### ISSUE TITLE
How will this package handle `@container` queries?

### ISSUE THREAD

**Issue by matthew-dean** [styled-components/css-to-react-native#168]
We're in the process of defining how our existing components (currently Styled Components for web) will be used with React Native. At the same time, [Container Queries are just around the corner](https://caniuse.com/css-container-queries), and I could see us integrating these when these land in all major browsers.

My understanding is that only Styled Components v6 will support Container Queries, and is still in beta. When all the above variables are satisfied (v6 released, Container Queries in browsers), how will this package handle those? Since container queries are extremely popular / desired among web developers, I imagine the adoption will be extremely rapid compared to past CSS features.

**Comment by matthew-dean** [comment]
It looks like something could be done with parsing the `@container` syntax into an observer for `onLayout` callbacks? https://reactnative.dev/docs/view#onlayout

**Comment by jacobp100** [comment]
This library doesn’t go that far. You gotta layer that stuff on top
