### ISSUE TITLE
[Feature request] Add support for viewport units

### ISSUE THREAD

**Issue by hyoretsu** [styled-components/css-to-react-native#184]
This was already implemented in a 3rd party lib called [rn-css](https://github.com/Sharcoux/rn-css), and it's easily doable on our end. But if we do it manually, it's a hassle to import and call vw/vh variables every single time.

**Comment by jacobp100** [comment]
Do you just want them written out to the exported style object?

**Comment by hyoretsu** [comment]
Rather, I want them converted to measures in RN. e.g. if I use `97 * vw` it can be translated to
```
import { Dimensions } from 'react-native';

97 * Dimensions.get('window').width / 100;
```

**Comment by jacobp100** [comment]
You’ll need to put a runtime in front of this library to do that

See what [Cssta](https://github.com/jacobp100/cssta) does
