### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mxstbr** [styled-components/css-to-react-native#2]
Not sure how much or little this module should do.

It could do the whole CSS string -> ReactNative object thing, but it could also just be responsible for the ReactNative specific styles:

```JS
import transform from 'css-to-react-native';

// ...

declarations.forEach(decl => { styles[decl.property] = transform(decl.value) })
```

In this case it would just check if it's one of the special reactnative declarations and then transform just those, otherwise return the value unchanged.

What do you think?

**Comment by jacobp100** [comment]
I think we should have the default export be string => style map, but also expose declaration[] => stylemap. I don't think it's safe to assume 1 declaration = 1 property, since it would be nice to allow shorthands at some point.

**Comment by mxstbr** [comment]
Sure, you go ahead then, I'm sure you've thought about this more than I have! :D

**Comment by jacobp100** [comment]
I’ve added API docs to the README. The only thing I’m wondering now is if we actually want to include postCSS at all. We could have the entire API be,

```js
transform([
  ['border-width', '3 4'],
  ['font', '12/18 "Helvetica"'],
]);
```

Which means people using it without postCSS could do so without bloat. Then people using postCSS can just do,

```js
transform(decl.map(decl => [decl.name, decl.value]));
```

Thoughts?

**Comment by mxstbr** [comment]
Sounds good to me!

**Comment by jacobp100** [comment]
Neat! Should be ready to publish—just run `npm run build` first!

**Comment by mxstbr** [comment]
Sorry man, I totally dropped the ball on this! Back on it, let's land this! 🎉

**Comment by mxstbr** [comment]
Published v1.0.0 and added you on npm!

**Comment by jacobp100** [comment]
@mxstbr Hi sorry. Would it be possible to run `npm build` and republish. It’s my fault, I should really learn how to use the npm publish scripts!

**Comment by mxstbr** [comment]
You can totally do that yourself, I've added you on npm, but I'll do it this time!

**Comment by jacobp100** [comment]
Just noticed that. Thanks! I’ve just added the prepublish hook now!
