### ISSUE TITLE
Units?

### ISSUE THREAD

**Issue by jacobp100** [styled-components/css-to-react-native#20]
RN now to supports percentages now. I.e. `{ height: "50%" }`. We actually mostly support this, so you can write `height: 50` or `height: 50%`, and both will work.

This makes it a little inconsistent, where sometimes you include a unit, and sometimes you don’t. We should try and achieve more consistency by forcing a unit when the value is a length. In the previous example, you would have to write `height: 50px`.

This would remove ambiguities in the `flex` shorthand, and would allow us to accept `line-height`s as a multiple of `font-size` in the `font` shorthand.

Not only that, but you could sort of share code between web and native.

```js
const Component = isWeb ? 'div' : View;
const StyledComponent = styled(Component)`
  height: 50px;
`;
```

This is obviously a breaking change, so we should look towards v2.

**Comment by jacobp100** [comment]
@mxstbr Thoughts?

**Comment by mrpatiwi** [comment]
+1

I think supporting units for React-Native (or just numbers in React web) could make `styled-components` a real universal styling library.

> Related to: https://github.com/styled-components/styled-components/pull/317

**Comment by mxstbr** [comment]
LGTM

**Comment by jacobp100** [comment]
Added in v2

**Comment by IljaDaderko** [comment]
@jacobp100 does this mean we must include px values now? I opened an issue #559 have a feeling that this might be related.

**Comment by tlvenn** [comment]
I understand the rational and the intention behind this but I find it a bit disturbing given RN does not use pixel unit at all... Quoting RN doc:
> All dimensions in React Native are unitless, and represent density-independent pixels.

**Comment by tlvenn** [comment]
It would honestly be super weird if all of the sudden we are forced to suffix 'px' unit in our RN projects...

**Comment by tlvenn** [comment]
Sorry for spamming this issue ;) Instead of using 'px' which I believe is the wrong unit for RN, why not use 'dp' ?
> https://material.io/guidelines/layout/units-measurements.html#units-measurements-density-independent-pixels-dp

**Comment by jacobp100** [comment]
In CSS, `px` doesn't mean physical device pixels. [(spec)](https://www.w3.org/TR/css3-values/#px)

**Comment by tlvenn** [comment]
Ha good point @jacobp100 , never realised that in the CSS spec `px` is density independent.

**Comment by flxwu** [comment]
Did you fix it @IljaDaderko ?

**Comment by toytonic** [comment]
Same here. I'm suddenly getting this error in production environment. How do I get around it? Specify all units with `px`?

**Comment by jacobp100** [comment]
Yep!

**Comment by omarkhaled11** [comment]
is there a codemod for this? the only codmod I could find [here](https://github.com/styled-components/styled-components-codemods) is for v4 and it doesn't including adding the units.

**Comment by jacobp100** [comment]
Yep - https://github.com/styled-components/styled-components-native-code-mod

**Comment by omarkhaled11** [comment]
@jacobp100 thanks a lot! Is there a way to enforce using units by linting tools? using eslint for example?

**Comment by jacobp100** [comment]
@kristerkari I know you had some linting tools. Do any of them lint units?

**Comment by kristerkari** [comment]
@jacobp100 Unfortunately not. I have been discussing the need of such linting rule, but the main problem is that it would be quite complex to get it working correctly for all the different types of properties in CSS.

https://github.com/stylelint/stylelint/issues/3208

**Comment by Sharcoux** [comment]
Just for information, the package [rn-css](https://www.npmjs.com/package/rn-css) does that with the same syntax as styled-components. It might be interesting to try to fusion the styled-components/native project and this?
