### ISSUE TITLE
React Native Shorthand notation in props

### ISSUE THREAD

**Issue by f0rr0** [styled-components/css-to-react-native#27]
Closing https://github.com/styled-components/styled-components/issues/517 and moving it here.

```js
const Button = styled(View)`
   margin: ${({ margin }) => margin};
`

// Expected usage with shorthands

const MyComponent = () => (
  <Button margin="10 20" />
)

// Above fails with: ExceptionsManager.js:71 JSON value '10 20' of type NSString cannot be converted to NSNumber
```

Possible duplicate: https://github.com/styled-components/styled-components/issues/403

**Comment by jacobp100** [comment]
This is an issue in styled-components—it is the bug you linked. We're producing the right output here (see [tests](https://github.com/styled-components/css-to-react-native/blob/ac4ee18ec5930c5ed28cd3843c5404fd81afc84e/src/index.test.js#L202-L204)).
