### ISSUE TITLE
undefined is not a function (evaluating 'tokenDescriptors[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')

### ISSUE THREAD

**Issue by brunolemos** [styled-components/css-to-react-native#31]
OS: Android only
Weird: Only happens when Remote JS Debugging is `disabled`
styled-components: v2.0.0-7
css-to-react-native: v2.0.1

```
undefined is not a function (evaluating 'tokenDescriptors[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
match
    TokenStream.js:45:29
exports
    flex.js:21:24
getStylesForProperty
    index.js:35:37
<unknown>
    index.js:49:53
default
    index.js:45:22
<unknown>
    InlineStyle.js:74:60
generateStyleObject
    InlineStyle.js:59:8
generateAndInjectStyles
    StyledNativeComponent.js:123:47
<unknown>
    StyledNativeComponent.js:91:65
subscribe
    create-broadcast.js:33:15
componentWillMount
    StyledNativeComponent.js:83:39
<unknown>
    ReactCompositeComponent.js:325:16
```

**Comment by mxstbr** [comment]
That's a bug on our side I think? We shouldn't have any Symbols in the compiled codebase.

**Comment by jacobp100** [comment]
Newest version published, easiest course is nuke your node_modules and try again! Let me know if there are further issues!

**Comment by brunolemos** [comment]
@jacobp100 thanks, that works!

I tried to open a pull request but instead I commited to v2 branch: https://github.com/styled-components/styled-components/commit/7e3c3040cf04648c77425507543432b0213676d5

Forgot I got write access. If you want to revert it no problem.

Thanks.
