### ISSUE TITLE
Generated stylesheet breaks, doesn't correctly change px to plain number

### ISSUE THREAD

**Issue by fxfactorial** [styled-components/css-to-react-native#36]
Given this: 

```jsx
const TaskScrollWrapper = styled.ScrollView`
  padding: 10;
  background-color: red;
`;

const NewTaskBanner = styled.Text`
  font-size: 18px;
  text-align: center;
`;

  const content = (
    <TaskScrollWrapper>
      <NewTaskBanner> Hello World</NewTaskBanner>
    </TaskScrollWrapper>
  );
```

Then I get an error with RN `"react-native": "0.42.0"`, this is with `"styled-components": "^1.4.5",`. 
<img width="511" alt="screen shot 2017-05-01 at 9 25 26 pm" src="https://cloud.githubusercontent.com/assets/3036816/25604978/a5572f64-2ebc-11e7-94e4-7482ce974214.png">

Of course it does work when I drop the 'px', Thanks.

**Comment by jacobp100** [comment]
Styled-components v1 is using v1 of this library. Unit support was only added in v2.

**Comment by fxfactorial** [comment]
@jacobp100 Okay, so besides closing is there any advice? I should just wait until styled-components catches up?

**Comment by jacobp100** [comment]
It's in SC v2, since it was a breaking change. Not sure what the timeline for that being released though!

**Comment by jacobp100** [comment]
Also you can omit units for now, and we have a [code transform](https://github.com/styled-components/styled-components-native-code-mod) to add them later.
