### ISSUE TITLE
Error: Failed to parse declaration "flex: 0 1"

### ISSUE THREAD

**Issue by apexskier** [styled-components/css-to-react-native#37]
The shorthand property
```
flex: 0 1;
```

Should be parsed to 
```
flex-grow: 0;
flex-shrink: 1;
```

reproduction on the node repl:
```js
require('css-to-react-native').default([['flex', '0 1']])
```

**Comment by jacobp100** [comment]
Thanks for finding this! It turned out to be zeros showing up as falsy values—and would have actually effected a lot more shorthands!
