### ISSUE TITLE
Any plans for adding support for units such as pt, em, etc?

### ISSUE THREAD

**Issue by gurs1kh** [styled-components/css-to-react-native#45]
Often for things like font size, it is much more common to see `pt` or `em` used instead of `px`. Are there any plans for adding support for these?

**Comment by jacobp100** [comment]
Maybe `pt`. `em` isn't feasible, since we don't have access to the current text size.

**Comment by jacobp100** [comment]
If you wanted to look at this, I suspect it's relatively straight forward: you'd just have to additionally capture `pt` in [`lengthRe`](https://github.com/styled-components/css-to-react-native/blob/master/src/tokenTypes.js), and add a transform that takes this into account.

**Comment by gurs1kh** [comment]
I'm having difficulty understanding the exact structure of the code, but from what I'm seeing, adding the capture to `lengthRe` wouldn't work since `regExpToken` would convert it into a `Number`, and get rid of the "pt" in the value passed. Assuming that's the case, a new token may be needed for this. Is this correct?

**Comment by jacobp100** [comment]
You'll need to swap out the `Number` part too! You could modify `regExpToken` to pass in all capture groups too if that makes it easier
