### ISSUE TITLE
does it support Platform.select?

### ISSUE THREAD

**Issue by sibelius** [styled-components/css-to-react-native#46]
in StyleSheet we can have this:

```jsx
separatorAndroid: {
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    ...Platform.select({
      ios: {
        height: 0,
        backgroundColor: '#ffffff',
      },
      android: {
        height: 10,
        backgroundColor: '#EEEEEE',
      },
    }),
  },
````

how this works on styled-components?

**Comment by jacobp100** [comment]
I think you have the wrong repo, but in SC, you can just interpolate this. 

```js
styled`
  color: ${Platform.select({ iOS: 'red', android: 'blue' })};
`
```

**Comment by grsabreu** [comment]
hey @jacobp100, first of all, thanks for the great lib! 

I know this is already closed, but do you think it would be out of the scope of `css-to-react-native` creating a `Platform.select` shorthand with this syntax:

```js
const Wrapper = styled.View`
 @media android { background-color: red; }
 @media ios { background-color: blue; }
`
```

or maybe

```js
const Wrapper = styled.View`
 @platform android { background-color: red; }
 @platform ios { background-color: blue; }
`
```

**Comment by jacobp100** [comment]
So this library just takes property and value pairs instead of blocks of CSS. You could ask on the styled-components repo—that shouldn't be too hard to implement.
