### ISSUE TITLE
:hover with react-native and react-native-web

### ISSUE THREAD

**Issue by achtan** [styled-components/css-to-react-native#48]
Hi, i'm using styled-components in react-native app
lets say i have Link component:

````js
    import styled from 'styled-components/native';

    const Link = styled.Text`
      color: 'red';

      &:hover {
        color: 'blue';
      }
    `
````
then i 'compile' my RN code with [react-native-web](https://github.com/necolas/react-native-web)

all is great expect that hover is not working (text color remains `red` on hover)

my guess is that css-to-react-native is removing the `hover` definition

any idea how to fix this?

**Comment by mxstbr** [comment]
`react-native-web` does not support pseudoselectors, `css-to-react-native` is not doing anything wrong here.

See https://github.com/necolas/react-native-web/blob/d1d570268a4f3fcccb6b73a88afaaf7f0dcb68ed/docs/guides/style.md#what-about-pseudo-classes-and-pseudo-elements

**Comment by achtan** [comment]
@mxstbr thx for quick answer, but can you double check, please
because this code is working:
````js
import * as React from 'react';
import {TouchableOpacity} from 'react-native';
import {StyleSheet as WebStyles, css} from 'aphrodite';

import Text from './Text';
const Link = ({onPress, textProps, children}) => {
  return (<TouchableOpacity onPress={onPress}>
    <Text className={css(webStyles.link)}  {...textProps}>
      {children}
    </Text>
  </TouchableOpacity>);
};

const webStyles = WebStyles.create({
  link: {
    ':hover': {
      color: 'blue'
    }
  },
});
export default Link;
````

**Comment by mxstbr** [comment]
Is that rendered to the web?

**Comment by achtan** [comment]
yes
```html
<div class="link_qja8gq *more classes*" dir="auto">link</div>
```
and ind `style` definition is
```css
.link_qja8gq:hover {
    color: blue !important;
}
```

**Comment by jacobp100** [comment]
It's a problem here:

https://github.com/styled-components/styled-components/blob/9c98a6edff9d13ac0a7851c52be156aea2d2a2ca/src/models/InlineStyle.js#L33-L40

**Comment by mxstbr** [comment]
Hmm, does `/primitives` use that though? /cc @mathieudutour

**Comment by mathieudutour** [comment]
not sure what this is but if it's working for `react-native` and `react-native-web`, it will work for `react-primitives`

**Comment by achtan** [comment]
hi, any update on this one? should i wait for fix? because at this point I can't use styled-components...

**Comment by mathieudutour** [comment]
Wait a second, if you use Aphrodite to create a css class and then render it on the web, then yes it will show a hover. Aphrodite doesn’t use `style`, it injects css directly in the html. `className` is not a valid prop for a react native view (hence not valid for react-primitives). 

So there is nothing wrong with styled-components/primitives, your code is just not primitive compatible.

**Comment by achtan** [comment]
so i cannot use styled-components in react-native compiled to web (with react-native-web) ?

**Comment by mathieudutour** [comment]
you can, but you need to use what works for react native

**Comment by achtan** [comment]
ok, but we have common components like Button, Link, Avatar... for web (react) and also for app (react-native)

so how should i define Link component that i can use on web and app, and i need hover effect on web... 

@mxstbr any suggestions ?

**Comment by mathieudutour** [comment]
you can use `Button.web.js` and `Button.ios.js` to define custom behavior on the platform you want. But when you use primitives, it should use things that work everywhere.

**Comment by achtan** [comment]
ok, so lets say i have:
_Link.app.js_
````js
import React from 'react';
import styled from 'styled-components/native';

const Link = styled.Text`
  color: 'red';
`

export Link
````

_Link.web.js_
```` js
import NativeLink from './Link.app.js'

const WebLink = NativeLink; //how to change RN Text to 'span' DOM tag ?
// or how to add :hover or other web specific stuff ?

export WebLink
````

**Comment by mathieudutour** [comment]
no no, you would have
_Link.web.js_
```js
import React from 'react';
import styled from 'styled-components';

const Link = styled.a`
  color: 'red';
`

export Link
```

_Link.js (default)_ 
```js
import React from 'react';
import styled from 'styled-components/native';

const Link = styled.Text`
  color: 'red';
`

export Link
```

**Comment by achtan** [comment]
thats not the way... i cannot duplicate the code...
my current Button is (and is not even finished):
````js
import * as React from 'react';
import PropTypes from 'prop-types';
import styledDom from 'styled-components';
import styled from 'styled-components/native';
import Icon from './Icon'

import {mapProp} from '../../theme/styledHelpers'


const pickButton = prop => props => props.theme.Button[props.tint][props.shape][prop]

const TouchableWrapper = styled.TouchableOpacity`
    display: ${props => props.width === 'block' ? 'block' : 'inline-block'};
`

const paddingHorizontal = (props) => props.width === 'wide' || props.size === 'large' ? 20 : 10
const Content = styled.View`
    flex-direction: row;
    justify-content: ${mapProp('alignContent', {
      center: 'center',
      left: 'flex-start',
      right: 'flex-end',
    })};
    
    align-items: center;
    background-color: ${pickButton('backgroundColor')};
    border-color: ${pickButton('borderColor')};
    border-width: 1px;
    border-style: solid;
    border-radius: ${props => props.rounded ? 60 : props.theme.Button.borderRadius};
    min-width: ${props => props.width === 'wide' ? 200 : 'auto'};
    height: ${props => props.size === 'large' ? 40 : 'auto'};
    padding-left: ${paddingHorizontal};
    padding-right: ${paddingHorizontal};
  
    &:hover {
      background-color: ${pickButton('backgroundColorHover')};
      border-color: ${pickButton('borderColorHover')};
    }
`

const ContentDom = Content.withComponent

const ButtonText = styled.Text`
    color: ${pickButton('textColor')};
  
    &:hover {
      color: ${pickButton('textColorHover')};
    }
`

const StyledIcon = styled(Icon)`
    color: ${pickButton('textColor')};
`

const LeftIcon = StyledIcon.extend`
    padding-right: 10px;
`

const StyledButton = ({tint, shape, width, size, rounded, value, leftIcon, alignContent, children}) => {
  let buttonText = children;
  if(value || typeof children === 'string') {
    buttonText = <ButtonText>{value || children}</ButtonText>
  }

  const touchableProps = {width};
  const contentProps = {tint, shape, rounded, width, size, alignContent};
  const textProps = {tint, shape};
  const leftIconProps = {tint, shape}

  if(typeof leftIcon === 'string') {
    leftIcon = <LeftIcon name={leftIcon} {...leftIconProps}/>
  } else if(leftIcon) {
    leftIcon = <LeftIcon {...leftIcon.props} {...leftIconProps} />
  }

  return (
    <TouchableWrapper {...touchableProps}>
      <Content {...contentProps}>{leftIcon}<buttonText.type {...textProps} {...buttonText.props} /></Content>
    </TouchableWrapper>
  )
};

StyledButton.propTypes = {
  children: PropTypes.oneOfType([PropTypes.element, PropTypes.string]).isRequired,

  leftIcon: PropTypes.oneOfType([PropTypes.element, PropTypes.string]),
}

StyledButton.defaultProps = {
  tint: 'default',
  shape: 'normal',
  alignContent: 'center'
}

export default StyledButton;
````

**Comment by jacobp100** [comment]
_Link.js (default)_ 
```js
import React from 'react';
import styled from 'styled-components/native';

export default styled.Text`
  color: red;
`
```

_Link.web.js_
```js
import React from 'react';
import styled from 'styled-components';
import BaseLink from './Link.js';

export default styled(BaseLink)`
  :hover {
    color: blue;
  }
`
```

**Comment by achtan** [comment]
> Wait a second, if you use Aphrodite to create a css class and then render it on the web, then yes it will show a hover. Aphrodite doesn’t use style, it injects css directly in the html. className is not a valid prop for a react native view (hence not valid for react-primitives).

> So there is nothing wrong with styled-components/primitives, your code is just not primitive compatible.

className is working fine, except `:hover {...}` definition

**Comment by mathieudutour** [comment]
just put what you want (can) to share in another file and import it?

**Comment by mathieudutour** [comment]
> className is working fine, except :hover {...} definition
no it doesn't: it's not doing anything on react native. What's the point of using primitives if it's to use them only on the web? a primitive is supposed to work the same way on every platform. If you want a special behavior (classes and hover), then you can use a `.web.js` file and `styled-components` to specify it.

**Comment by achtan** [comment]
thx @jacobp100 your approach is working fine!

**Comment by achtan** [comment]
OK, so i am back unfortunately... :/
so when i modify the @jacobp100 's code like this:

Link.js (default)
```js
import React from 'react';
import styled from 'styled-components/native';

const StyledText = styled.Text`
    color: red;
`

export default Link = ({ children }) => {
  return <StyledText>{children}</StyledText>;
};
````

Link.web.js
```js
import React from 'react';
import styled from 'styled-components';
import BaseLink from './Link.js';

export default styled(BaseLink)`
  :hover {
    color: blue;
  }
`
```

color is not changed to blue on hover...

html output: 
```html
<style type="text/css" data-styled-components="heyOvl" data-styled-components-is-local="true">
    /* sc-component-id: sc-bwzfXH */
    .sc-bwzfXH {}
    .heyOvl:hover{color:blue;text-decoration:underline;}
</style>

...
...

<div dir="auto" class="rn-borderTopWidth-13yce4e rn-borderRightWidth-fnigne rn-borderBottomWidth-ndvcnb rn-borderLeftWidth-gxnn5r rn-color-1lbce71 rn-display-1471scf rn-font-1lw9tu2 rn-marginTop-1mnahxq rn-marginRight-61z16t rn-marginBottom-p1pxzi rn-marginLeft-11wrixw rn-paddingTop-wk8lta rn-paddingRight-9aemit rn-paddingBottom-1mdbw0j rn-paddingLeft-gy4na3 rn-textDecoration-bauka4 rn-whiteSpace-q42fyq rn-wordWrap-qvutc0">
    Hellloooo
</div>
````

**Comment by brunolemos** [comment]
@achtan 
```diff
-:hover
+&:hover
```

**Comment by georgii-ivanov** [comment]
Having the same issue:

https://github.com/styled-components/styled-components/issues/3323

Could you please take a look at this issue again?
Because you can actually keep in your hashed stylesheet :hover and other css-specific declarations.
Nobody's asking there to port those to get that worked on react-native.

**Comment by flyskywhy** [comment]
Maybe you can ref to my answer in [onmouseenter event in react native](https://stackoverflow.com/a/66204539/6318705)

**Comment by Sharcoux** [comment]
You guys might want to try [rn-css](https://www.npmjs.com/package/rn-css) that is handling hover and a bunch of other features to have a common CSS between RNW and RN.
