### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by mxstbr** [styled-components/css-to-react-native#5]
Would be great to add the same linting we have over at the main repo to make sure the code style is consistent and switching between repos isn't a hard context switch due to superficial code style differences.

We can probably just copy the `.eslintrc` from the main repo.

**Comment by jacobp100** [comment]
Feel free!

**Comment by mxstbr** [comment]
Oh I just saw we already have linting. Nevermind, closing!

**Comment by jacobp100** [comment]
I don’t mind if you want to make it match the main project—I’m mostly going to work on `grammar.ne` anyway!
