### ISSUE TITLE
Thought this was CSS to react native StyleSheet object?

### ISSUE THREAD

**Issue by NordlingArt** [styled-components/css-to-react-native#50]
The module does the exact opposite. You take StyleSheet object and turn it into a CSS string with the transform function:

```js
import CSS from "css-to-react-native";

CSS({
    test: {
        color: "#ff0000"
    }
}); // Returns CSS string: ".test { color: #ff0000; }"
```

But I thought this is what it was supposed to do:

```js
import CSS from "css-to-react-native";

CSS(`
    .test {
        color: #ff0000
    }
`); // Should return: { test: { color: "#ff0000" } }
```

What am I missing? There is nothing documented on how to actually convert CSS to a React Native StyleSheet object.

Thanks in advance!

**Comment by jacobp100** [comment]
Look at the readme for the docs! It does convert css to react native objects.

Note that it only converts css declarations, not rules. You’ll want to look into styled-components for how that’s done.

**Comment by brunolemos** [comment]
@jacobp100 @NordlingArt any hidden way to do the opposite? rn obj to css string?
Tried the code above but didn't work. Also didn't find this on the source code

**Comment by brunolemos** [comment]
Ok I see styled-components implemented a simple [objToCss](https://github.com/styled-components/styled-components/blob/d5b265e298dcfae38da7ff3aaba6bdc7f013466d/src/utils/flatten.js#L7) that only hyphenate the word... maybe that's enough

**Comment by jacobp100** [comment]
This package won’t do that.
