### ISSUE TITLE
Unsupported CSS fails silently

### ISSUE THREAD

**Issue by Zacqary** [styled-components/css-to-react-native#54]
Working with `styled-components` and `react-native-web` can be frustrating, because things like:

```js
const StyledView = styled(View)`
  &:hover { /* some hover state */ }
`
```

will just refuse to compile on the web without throwing an error. It'd be really helpful for multi-platform projects to know when our web-specific syntax is getting stripped so that we can refactor correctly.

**Comment by jacobp100** [comment]
Could you open this on the main styled-components repo? If you look at the API, this only takes pre-parsed declarations, so is out of the scope of css-to-react-native to fix. Thanks! 🙂

**Comment by Zacqary** [comment]
Sure thing, reopening there. Sorry about that
