### ISSUE TITLE
boxShadow transform does not support rbg, rgba, hsl or hsla colors 

### ISSUE THREAD

**Issue by kristerkari** [styled-components/css-to-react-native#59]
Currently `box-shadow` transform does not support `rgb`, `rgba`, `hsl` or `hsla` colors. 

Here are a few test cases that are failing:

```js
it('transforms box-shadow with rgb color', () => runTest([
  ['box-shadow', '10px 20px rgb(100, 100, 100)'],
], {
  shadowOffset: { width: 10, height: 20 },
  shadowRadius: 0,
  shadowColor: 'rgb(100, 100, 100)',
}));

it('transforms box-shadow with rgba color', () => runTest([
  ['box-shadow', '10px 20px rgba(100, 100, 100, 0.5)'],
], {
  shadowOffset: { width: 10, height: 20 },
  shadowRadius: 0,
  shadowColor: 'rgba(100, 100, 100, 0.5)',
}));

it('transforms box-shadow with hsl color', () => runTest([
  ['box-shadow', '10px 20px hsl(120, 100%, 50%)'],
], {
  shadowOffset: { width: 10, height: 20 },
  shadowRadius: 0,
  shadowColor: 'hsl(120, 100%, 50%)',
}));

it('transforms box-shadow with hsla color', () => runTest([
  ['box-shadow', '10px 20px hsla(120, 100%, 50%, 0.7)'],
], {
  shadowOffset: { width: 10, height: 20 },
  shadowRadius: 0,
  shadowColor: 'hsla(120, 100%, 50%, 0.7)',
}));
```

In addition to that, `shadowOpacity` property set to value `1` should probably be added by default to make sure that the shadow is always visible. I tested it, and I can confirm that the opacity for the shadow can be controlled by using `rgba` or `hsla` color's alpha value, so there is no need for `shadowOpacity` to be something else than `1`.

@jacobp100 @mxstbr

**Comment by jacobp100** [comment]
Thanks for the tests!

I think the immediate fix is to do `tokenStream.matches(tokenTypes.COLOR)` in [boxShadow.js](https://github.com/styled-components/css-to-react-native/blob/master/src/transforms/boxShadow.js).

Definitely the right call on always adding the shadow opacity.

Happy to accept a PR, otherwise I can get to this at the end of the weekend!

**Comment by kristerkari** [comment]
Thanks @jacobp100.

I can have a look at implementing a fix, but I don't fully understand how the parsing of the values works. 

Right now `tokenStream.lastValue` is used in `boxShadow.js` to get the color value. When using `rgb()` that lastValue is `null` and there is a value for `lastFunction` instead.

Is there something existing that allows me to retrieve the function as a string, or would I need to implement something to do that?

**Comment by kristerkari** [comment]
I managed to figure it out :) PR #60

**Comment by jacobp100** [comment]
Sorry, I should clean up the token stream.

I was mostly copying how it’s done in the rust CSS parser, but rust lets you do `if let value = stream.match(…)`. Not sure if the nicest way to do this in JS!
