### ISSUE TITLE
font-family Property

### ISSUE THREAD

**Issue by jacobp100** [styled-components/css-to-react-native#6]
Currently, when you define `font`, you currently have to wrap the font family in quotation marks: `font: 12 “Helvetica”`. When you define the `font-family` property, you define it without quotes: `font-family: Helvetica`. There is an inconsistency between the two.

The CSS spec has confusing behaviour, where you can omit quotes in some cases. ([See valid family names here](https://developer.mozilla.org/en/docs/Web/CSS/font-family)).

We can either require quotes on both of these properties, which will break existing code, or follow the spec by allowing some font names to be defined without quotes.

**Comment by mxstbr** [comment]
Sorry, how are we breaking the CSS spec? Which part is in ReactNative and which in CSS?

**Comment by jacobp100** [comment]
Updated comment.

**Comment by mxstbr** [comment]
That's weird. I'd hate to break existing code!

I would much rather follow the spec or be even looser to make sure developers don't get bitten by spec weirdness. What do you think, can we just allow both quotes and not quotes in all instances?

**Comment by jacobp100** [comment]
I just did a branch: [this test](https://github.com/styled-components/css-to-react-native/pull/7/files#diff-2382a7144b80bd7c6cfe69ed37c02f0cR293) shows existing code breakage. I’d wonder how many would be affected by that—I don’t think there are any system font names that would break.

I’m worried that if we don’t follow the spec, there could be a grammar ambiguity later that might be harder to reverse. I can’t think of any immediately, and it is entirely possible that there are none.

**Comment by mxstbr** [comment]
You might be right, but we can only publish this as a major version of both `css-to-react-native` and `styled-components`, so let's ship this whenever we get around to v2 of `styled-components`?

**Comment by jacobp100** [comment]
Sure!

**Comment by jacobp100** [comment]
Added in v2
