### ISSUE TITLE
Text-shadow styles not working

### ISSUE THREAD

**Issue by andreiciceu** [styled-components/css-to-react-native#68]
Hello,

I tried adding a text-shadow to a Text styled component, by using this code
```jsx
export const AppName = Text.extend`
  ${{
    textShadowColor: 'black',
    textShadowOffset: { width: -4, height: 1 },
    textShadowRadius: 14,
  }}
`;
```
Unfortunately, this does not work (tested on iOS with latest version of styled components).
As a workaround, I don't use styled-componenets for that particular component.

Any solution?
Many thanks

**Comment by jacobp100** [comment]
I opened your issue over [here](https://github.com/styled-components/styled-components/issues/1509). I'll close the issue here, because it's better suited to the other repo.
