### ISSUE TITLE
Warning: "fontVariant" is not a valid style property.

### ISSUE THREAD

**Issue by jpgorman** [styled-components/css-to-react-native#76]
I've been using the latest version of react-native-web, which uses css-to-react-native. I've noticed that when I use the short-hand `font: bold 14px/16px 'Helvetica';` that I get the following warning

```
Warning: "fontVariant" is not a valid style property.

StyleSheet generated: {
  "color": "#333",
  "fontStyle": "normal",
  "fontWeight": "bold",
  "fontVariant": [],
  "fontSize": 14,
  "fontFamily": "Helvetica",
  "lineHeight": 16
}
```

I'm using react-native: ^0.53.0

**Comment by kristerkari** [comment]
Any further info on how to reproduce the warning?

At least I can not see it when I use react-native 0.53.0,  the latest version of `css-to-react-native` and `font: bold 14px/16px 'Helvetica';` on a `<Text />`

**Comment by kristerkari** [comment]
Oh yeah, now that I read the description again I see that you mentioned `react-native-web`. Where is the warning coming from? Web browser?

**Comment by jacobp100** [comment]
[Filed an issue in react-native-web](https://github.com/necolas/react-native-web/issues/824)
