### ISSUE TITLE
Support "margin: 0 auto;"

### ISSUE THREAD

**Issue by kristerkari** [styled-components/css-to-react-native#77]
Using `margin: 0 auto;` throws an error.

Here's a unit test to copy/paste:

```js
  expect(transformCss([['margin', '0 auto']])).toEqual({
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
  })
```

**Comment by jacobp100** [comment]
Good catch! We’ll need to support top/bottom as well, so it should be pretty easy to update in `transforms/index.js`
