### ISSUE TITLE
Could this module be the home for RN media query support ?

### ISSUE THREAD

**Issue by tlvenn** [styled-components/css-to-react-native#8]
Hi,

Following on the issue I opened there: https://github.com/styled-components/styled-components/issues/203 could this new module dedicated to RN be the home to support media query on RN ?

It will likely bring some dependencies so I am wondering if we want to have RN material all in one module (this one ?) or should we create specialized RN modules ?

**Comment by jacobp100** [comment]
Styled-components would be the best bet for this issue. I’ll close this, and the discussion can continue on the other thread.
