### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by corysimmons** [styled-components/css-to-react-native#80]
Like, is there a way to write something like:

```css
/* Buttons.css.js */
export const primary `
  background-color: green;
  padding: 15px 30px;
`

export const danger `
  background-color: red;
  padding: 15px 30px;
`
```

```jsx
/* Form.js */
import * as Buttons from './css/Buttons.css'

<Text style={Buttons.primary}>Submit</Text>
<Text style={Buttons.danger}>Delete</Text>
```

And have css-to-react-native transform it somehow?

Sorry, I see how it works for people who might want to write a plugin for it, but not for casual users just trying to avoid writing standard RN style objects.

**Comment by jacobp100** [comment]
We are more aimed at plugins. Generally you'd use this with postcss or another CSS parser. Have a look what they do in [styled-components](https://github.com/styled-components/styled-components/blob/b9e8a1f4631b4eb20940b5123ca7736ac3e7322e/src/models/InlineStyle.js#L27-L63).

**Comment by corysimmons** [comment]
If it's somewhat trivial to expose to something similar to my use case can this issue be converted to a feature request? If not, go ahead and close.

**Comment by jacobp100** [comment]
CSS parsers are usually pretty hefty, so adding one would have a huge impact on this library's size. Besides that, all the projects using this do different things with CSS anyway, so there's not really a universal solution to this.

Hope this helps!

**Comment by mxstbr** [comment]
If you want to avoid writing standard RN style objects then please use `styled-components`, which lets you write CSS as you're used to on the web.

If you're not happy with the API that s-c exposes then feel free to write your own wrapper around `css-to-react-native`, but offering more APIs is definitely out of scope of this package :blush:

**Comment by corysimmons** [comment]
styled-components doesn't support media queries in RN.

SC has a really nice approach, but the 2 things I want from it: media queries in RN (required) and PostCSS (a nicety), are shot down as "doesn't interest us [closed/locked]".

So... yeah, if I get time I'll take a shot at implementing my own. Until then I'm stuck with react-native-extended-stylesheet and ugly POJO css.

I was hoping with this lib I could at least sidestep the POJO stuff.

Not upset. Just poking to see what needs built.

**Comment by jacobp100** [comment]
If you want to live on the edge, check out [cssta](https://jacobp100.github.io/cssta/native/). We have media queries in the master branch (so add the git repo over the npm package as your dependency)

**Comment by corysimmons** [comment]
@jacobp100 Looks awesome! I'm behind deadline on this project but should have it done in a week or two, then I should have a bit of time to contrib. :D
