### ISSUE TITLE
Failed to parse declaration "transform: translateY(100%)

### ISSUE THREAD

**Issue by zomars** [styled-components/css-to-react-native#82]
It seems like percentage values are failing on transforms.

**Comment by jacobp100** [comment]
React Native doesn’t support percentages for transforms. Hope this helps!

**Comment by zomars** [comment]
Is this documented somewhere? I couldn't find any info about this.

**Comment by jacobp100** [comment]
It’ll be in the react native docs. For translations, they only accept numbers (aka pixel distances).
