### ISSUE TITLE
Handling of line-height with a multiplier value

### ISSUE THREAD

**Issue by kristerkari** [styled-components/css-to-react-native#89]
Currently with a multiplier value for `line-height`:

```js
transformCss([['line-height', '1.5']])
```
The result is this:

```js
{ lineHeight: 1.5 }
```

React Native treats it as a pixel value instead of a multiplier. We can only calculate the multiplier if we know the font-size of the `Text` element. 

Maybe we should only allow pixels (or other units) to be used with `line-height` and throw an error for a multiplier?

ping @jacobp100

**Comment by jacobp100** [comment]
It’s just going through the generic remove-px route. Maybe we could just warn/throw an exception on dev for this case
