### ISSUE TITLE
Upgrade node-fetch to >= 2.3.0 to fix semantic-release users that use styled-components

### ISSUE THREAD

**Issue by kopax** [styled-components/css-to-react-native#98]
## Environment

We are experiencing issue on travis while using semantic-release.

This happen because of a package having being fixed `node-fetch@2.3.0` for semantic-release to work and styled-components having an outdated node-fetch through [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch/issues/new).

Users that use both semantic-release and styled-components will have issues. 

- https://github.com/semantic-release/github/issues/129
- https://github.com/semantic-release/semantic-release/issues/995

## Related issues:

- https://github.com/styled-components/styled-components/issues/2247#issuecomment-442114941
- https://github.com/styled-components/css-to-react-native/issues/98
- https://github.com/facebook/fbjs/issues/325
- https://github.com/matthew-andrews/isomorphic-fetch/issues/179

## Reproduction

https://travis-ci.org/yeutech-lab/rollup-umd-documentation/jobs/459847412

```bash
$ npm ls node-fetch
@yeutech-lab/rollup-umd-documentation@2.4.2 /home/dka/workspace/github.com/yeutech-lab/rollup-umd-documentation
├─┬ @semantic-release/github@5.2.5
│ └─┬ @octokit/rest@16.0.1
│   └── node-fetch@2.3.0 
└─┬ styled-components@4.1.1
  └─┬ css-to-react-native@2.2.2
    └─┬ fbjs@0.8.17
      └─┬ isomorphic-fetch@2.2.1
        └── node-fetch@1.7.3 
```

## Steps to reproduce

- semantic-release: v15.12.1
- styled-components: v4.1.1

## Expected Behavior

To have `node-fetch@2.3.0`

## Actual Behavior

Styled-components bring `node-fetch@1.7.3` and breaks semantic-release.

## Solution

- **short term**: `npm install node-fetch@2.3.0 --save-dev`
- **long term**: Upgrade chain of dependencies, require help of https://github.com/matthew-andrews/isomorphic-fetch/, https://github.com/facebook/fbjs, https://github.com/styled-components/css-to-react-native/ and https://github.com/styled-components/styled-components

**Comment by jacobp100** [comment]
Looks like we need to update `fbjs` to `1.0.0`. I won't have a tonne of time over the next few weeks, but I'll be happy to accept a PR - it should be pretty quick to fix!

**Comment by kopax** [comment]
I don't think this will solve the problem, except if they do not rely on isomorphic-fetch (which doesn't exist with node-fetch v2) or any dependencies that rely on fetch v1.

**Comment by jacobp100** [comment]
Okay. We only use fbjs for the camel-case conversion, and it looks like that just uses `camelize` (with some browser workarounds that we don't need). I'd be happy to replace the dependency if that fixes it?

**Comment by mxstbr** [comment]
@jacobp100 that sounds like a great plan, let's do that!

**Comment by kopax** [comment]
@jacobp100 I didn't go that far but if you are positive that the lib is just there for that, yeah that sound great let's do that.

**Comment by kopax** [comment]
I've just pushed the proposed fix by jacobp100. I also add to remove the `package-lock.json` file as you do not need that.
